#pragma once

#define GL_GRAVITY 0.1f

#define GL_PARTICLE_NUMBER_BLAST 64
#define GL_PARTICLE_NUMBER_TOTAL 2048
#define GL_PARTICLE_EFFECTS_TOTAL 2048

#define GL_PARTICLE_BLAST_CHANCE_PERC 2

#define GL_PARTICLE_MIN_LIFE_MS 2000.f
#define GL_PARTICLE_MAX_LIFE_MS 10000.f

#define GL_PARTICLE_MAX_WEIGHT 10.f
#define GL_PARTICLE_MIN_WEIGHT 1.f

#define GL_PARTICLE_MIN_SPEED 0.1f
#define GL_PARTICLE_MAX_SPEED 0.5f

#define GL_THREAD_NUMBER 2

#define GL_MAX_DELTA_DELAY 30.f



